
HexanowLang = Explorite.SimpleTranslate()

HexanowLang.data.en.active = "active"
HexanowLang.data.zh.active = "主动"
HexanowLang.data.en.passive = "passive"
HexanowLang.data.zh.passive = "被动"
HexanowLang.data.en.glitched_item = "Glitched item {1}"
HexanowLang.data.zh.glitched_item = "错误物品{1}"
HexanowLang.data.en.glitched_item_desc = "A corrupted {1} item that generated by TMTRAINER effect."
HexanowLang.data.zh.glitched_item_desc = "被错误技效果生成的损坏{1}物品。"
HexanowLang.data.en.empty_slot = "Empty slot"
HexanowLang.data.zh.empty_slot = "空槽位"
HexanowLang.data.en.empty_slot_desc = "Can store an item."
HexanowLang.data.zh.empty_slot_desc = "可以容纳一个物品。"
HexanowLang.data.en.discard_slot = "Discard slot"
HexanowLang.data.zh.discard_slot = "丢弃槽位"
HexanowLang.data.en.discard_slot_desc = "Destroy items for eternal charges."
HexanowLang.data.zh.discard_slot_desc = "摧毁物品以获取永恒充能。"
